### ISSUE TITLE
EV3-G API: ultrasonic sensor

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#364]
Need to get screenshots of the ultrasonic sensor blocks

**Comment by dlech** [comment]
![image](https://user-images.githubusercontent.com/963645/30654430-740c9286-9df3-11e7-87ed-4beca79df297.png)

**Comment by dwalton76** [comment]
Any of you guys own one of these? I do not

**Comment by WasabiFan** [comment]
Yeah, I have a few. I'll see if I can find one and implement this later today.

**Comment by WasabiFan** [comment]
I'm taking a look at this now and realizing that we already have almost all of this. The distances are properties called`distance_inches` and `distance_centimeters`, and presence is ` other_sensor_present`. We don't have measuring modes though (I don't fully understand that). Do we want to rename these to be more literal translations?

**Comment by dwalton76** [comment]
yeah I'm not sure what `ping` vs `continuous` really means...it could only be `continuous` for so long because eventually you have to return an answer.  I just found a youtube video on it....watching

**Comment by dwalton76** [comment]
LOL well the guy in the video said "I haven't really experimented much with the advanced ping vs continuous thing"

**Comment by dwalton76** [comment]
ok found something
https://forums.usfirst.org/forum/general-discussions/first-programs/first-lego-league/the-challenge/programming-ab/12738-ev3-helpful-hints/page6

> The Advanced XXX mode is similar to the Measure Distance - XXX mode, except that you can choose whether the sensor sends a single ultrasonic signal or continuous signals with the Measuring Mode input. The distance in XXX is output in the Distance.
> 
> When in advanced mode you can program the sensor to generate a single ping each time the sensor block is executed. In this mode the sensor is not active unless you are actually reading the sensor value. In continuous ping mode the sensor pings continuously in the background and the latest result is stored in a buffer. When you read the sensor the block accesses the value in this buffer.

**Comment by dlech** [comment]
continuous means that the ultrasonic sensor is continuously sending out a sound signal. If you have multiple sensors they will interfere with each other. Ping means that the sensor does one measurement and then turns off the speaker. This allows multiple sensors to take turns without interfering with each other.

in order to get the ping to work, you have to set the mode each time you want to ping.

**Comment by dwalton76** [comment]
@WasabiFan I think you started on this one correct?  If not I have an UltraSonic sensor now and can take a stab at it.

**Comment by WasabiFan** [comment]
@dwalton76 yeah, I started on it but it wasn't too far along; it was pretty much just a new class with one property, I think. If you have the cycles to take it on, go for it! That would be much appreciated. Otherwise the next available breathing room when I might be able to take this on is the first weeks of December. Apologies for dragging it out!

**Comment by dwalton76** [comment]
@WasabiFan looks like we both got swamped through December :)  I'll take a stab at it

**Comment by WasabiFan** [comment]
😖 Yeah, it seems that new work always appears to fill the gaps. I _will_ be carving out some time over the next week or so to knock some things off the list.
