### ISSUE TITLE
How to program HiTechnic servo with HiTechnic Servo Controller for TETRIX

### ISSUE THREAD

**Issue by rexlow** [ev3dev/ev3dev-lang-python#430]
- **ev3dev version:** 4.4.87-22-ev3dev-ev3

I am trying to program a servo so that is it able to position itself to a number of degree. In order to achieve this, I understand that it first has to connected with a servo controller so that data transmission is possible.

This is my setup. As depicted from the image below, DC Controller is connected to `input 2` and Servo Controller is connected to `input 3`. 

![img_0571](https://user-images.githubusercontent.com/7680796/32662703-65c4bd20-c666-11e7-9c61-d1c2e0bdfb06.JPG)

My goal is to manipulate `servo` that is connected to `channel 1`. I was able to rotate the `dc motor` but not  the servo. 

**Code**
```
>>> import smbus
>>> dc = smbus.SMBus(4)
>>> servo = smbus.SMBus(5)
>>> dc.write_i2c_block_data(0x01, 0x46, [0x30])         # motor rotates
>>> servo.write_i2c_block_data(0x01, 0x42, [0x30, 0x55])    # servo did not react
```

I am confident that the number of addresses and registers are correctly configured. I tried to write and read block data multiple times and it shows that data is being written in the correct channel.
```
>>> print(servo.read_i2c_block_data(0x01, 0x42))
[48, 85, 90, 91, 128, 128, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

So the question is, how can I control the position of the servo and what exactly does the third parameter array means (180 degree span across 32 bits of character?)

Regards,
Rex.

**Comment by dlech** [comment]
Have you tried setting register 0x48? The docs say it has to be set to 0x00 to enable the servos, but in your output, it is 255 (0xff).

http://www.hitechnic.com/blog/wp-content/uploads/HiTechnic-Servo-Controller-Specification.pdf

**Comment by rexlow** [comment]
@dlech Yes, I did and this is the output.
```
>>> servo.write_i2c_block_data(0x01, 0x48, [0x00])
>>> servo.write_i2c_block_data(0x01, 0x42, [60])
>>> servo.write_i2c_block_data(0x01, 0x42, [60, 90])
>>> servo.write_i2c_block_data(0x01, 0x42, [30, 60, 90])
>>> servo.read_i2c_block_data(0x01, 0x42)
[30, 60, 90, 128, 128, 128, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

Though I am not sure whether the array data I am passing is correct or wrong.

**Comment by dlech** [comment]
I read the docs a bit more carefully and it says that if you set register 0x48 to 170 (0xaa), then it disables the 10 second timeout that causes 0x48 to revert back to 255.

Also a couple tips...

    # write a single byte
    servo.write_byte_data(0x01, 0x48, 0xaa)

    # read less than 32 bytes
    servo.read_i2c_block_data(0x01, 0x40, 9)

**Comment by rexlow** [comment]
Eventually, we went through this [guide](http://www.openrtm.org/openrtm/ja/content/tetrix_ev3) thoroughly and successfully made the servo mode! 

Though we definitely need to study more about the relationship between the bytes and rotation angle. There are 32 sizes in one register, do we need to modify all of them in order to rotate a specific amount of angle?

Regards,
Rex.

**Comment by dlech** [comment]
There are not 32 bytes in a register. 32 is just the maximum size of a smbus message and you did not specify a smaller size when reading.

**Comment by perldeniel** [comment]
@rexlow  @dlech I sorta have this problem too! Coming from a CS background I do not have any prior knowledge on how to configure motors and servos, so sorry if my question sounds dumb.

> Do we need to specify PWM frequency, to set rotation angle? 

> Sure we can read data off the servo with `read_i2c_block_data` but how can we read current servo degree?

@rexlow If I do what you did to set servo degree, as `write_i2c_block_data`, does `[0x30]` means 30 degree? Does `[60, 90]` means servo rotates from 60 degree to 90 degree?

**Comment by dlech** [comment]
First, to be clear, I am only talking about hobby-type servo motors here. https://en.wikipedia.org/wiki/Servo_(radio_control)

> Do we need to specify PWM frequency, to set rotation angle?

Actually, you change the duty cycle, not the frequency. These types of motors use a 50Hz signal (one pulse every 20ms) for control. The width of this pulse tells the motor which angle to rotate to. 1.5ms is the "neutral" position. 1.0ms is the minimum rotation and 2.0ms is the maximum rotation.

 
> Sure we can read data off the servo with read_i2c_block_data but how can we read current servo degree?

You can't know the exact position of the servo motor. It does not have any feedback. You can only know what position you have requested it to move to. It may or may not have yet reached that position though (and may never reach it if it is blocked).


> If I do what you did to set servo degree, as write_i2c_block_data, does [0x30] means 30 degree? Does [60, 90] means servo rotates from 60 degree to 90 degree?

The docs say:

> The Servo 1/2/3/4/5/6 position fields will accept a value between 0 – 255 to set the PWM 
output from 0.75 – 2.25ms. Note that some servos may hit their internal mechanical 
limits at each end of this range causing them to consume excessive current. 

So, you need to do some math to translate. Suppose you have a servo that can travel 180 degrees. We will call the neutral position 0 degrees and the minimum and maximum -90 and 90 degrees respectively (90 - (-90) = 180). Here is a generic scaling function:

```
                      (out_max - out_min)
out = (in - in_min) * ------------------- + out_min
                       (in_max - in_min)
```

So, if we want to go to 30 degrees, that would translate to a 1.67ms pulse width (I trust that you can figure out the math). Then translating that again using the info from the user manual, we get that 1.67ms becomes 170, so we need to write 170 to the controller to get 30 degrees on the motor. (Of course, in your program, you could simplify this to only one conversion instead of calculating the intermediate pulse width).

The reason the controller goes beyond the 1.0 - 2.0ms range I described above is that these motors generally use analog circuits and are not exact. You may need to "calibrate" the motor by telling it to go 90 degrees. If it is not actually 90 degrees, keep adjusting the value you send to the motor controller until you get exactly 90 degrees and save that number to use as `out_max`. Then do the same for -90 degrees to get the minimum value.

**Comment by tassosblackg** [comment]
I followed the above guide http://www.openrtm.org/openrtm/ja/content/tetrix_ev3
but my servo doesn't rotate at all (I have one servo connected to channel1)
here is my testCode:

```C
        int fd = open("/dev/i2c-6",O_RDWR);
        printf("FILE discriptor : fd=%d\n",fd);
        if(fd>0)
        {
                ioctl(fd,I2C_SLAVE,0x02);
                unsigned char buf[2]={0x48,0xAA}; //PWM enable to 170
                write(fd,buf,2);
                
                unsigned char buf2[2]={0x42,0x7F}; //set value 127
                write(fd,buf2,2);
        }
```

any ideas?

**Comment by dlech** [comment]
@soylisK 

You have set your servo to the neutral position (127), so if it is already there, it won't move. So, it could be that your code works.

I suspect that if you check the return value of `write`, there will be an error though. I think the I2C device node is only usable via IOCTL.

Regardless, I would suggest using the `i2c_smbus_*` functions instead of trying to do low-level I2C calls. https://xgoat.com/wp/2007/11/11/using-i2c-from-userspace-in-linux/

**Comment by rexlow** [comment]
Is it possible to reverse voltage polarity (servo direction)? The official specification did not mention about it.

**Comment by dlech** [comment]
> Is it possible to reverse voltage polarity (servo direction)?

What type of motor and which controller are you using?

**Comment by rexlow** [comment]
@dlech I am using HS-485HB and HiTechnic Servo Controller for TETRIX.

**Comment by tassosblackg** [comment]
I have the same components, 
I'm still working on it.. and I believe that it's about how we set the buffer[] ={address,value..}?
because I'm facing some difficulties with dc motors too, about how to make them work properly .And I still haven't found something ...For example when we have more (servos or in case of motors we have 2 of them) how we set the buffer[] with appropriate values for each one (motor) and write() all at once?
e.g: buffer[4]={motor's1_address, power_value,motor's2_address,power_value}; //it doesn't seem right..?!
write(fd,buffer,4);
In somehow we have to define which data are address, and which are values and seperate between multiple channels..

**Comment by dlech** [comment]
>> Is it possible to reverse voltage polarity (servo direction)?
>
> @dlech I am using HS-485HB and HiTechnic Servo Controller for TETRIX.

Please see my previous [comment](https://github.com/ev3dev/ev3dev-lang-python/issues/430#issuecomment-345017609). Any value above 127 will rotate in one direction and any value less that 127 will rotate in the opposite direction.

**Comment by dlech** [comment]
@soylisK again, please use the `i2c_smbus_*_data()` functions instead of `write()`.

**Comment by rexlow** [comment]
@dlech We finally got everything works consistently. The errors occurred were due to the spoilt controller connector we were using. Changed a new one and now all our code works. Thanks for the thorough explanation!

**Comment by nshanis** [comment]
Hi, I have a problem on moving the servo to a certain value, using ev3dev python too. I tried following OpenRTM's website but I'm still clueless as to bringing the servo to move like it would on LabVIEW.
