### ISSUE TITLE
Motors not stopping at the same time?

### ISSUE THREAD

**Issue by thFury** [ev3dev/ev3dev-lang-python#468]
4.4.87-22-ev3dev-ev3
I have no idea what version of ev3dev-lang-python I'm using (if there's a specific command to find out tell me).

I'd update but I never got the internet working, it only shows me the 'connected' status with both DHCP and windows defaults.

The issue is that I tell the motors to stop: the first one stops, the second has a bit of delay, making my straight program useless.. Is there any way to fix this?

**Comment by WasabiFan** [comment]
It looks like we missed responding to this issue. Sorry about that! For future readers:

The slight delay is likely a result of the fact that the EV3's processor is quite slow, and the method of stopping one motor then the other has a significant amount of incurred overhead between the two low-level driver calls. This methodology will leave enough time between when the driver acts on the first request and when it acts on the second that there are noticable effects. The ideal solution requires built-in motor teaming support in the ev3dev driver, but that isn't immediately on the horizon. The next-best solution is:

- If you're on ev3dev-stretch (currently, the Python library for Stretch is only available from GitHub), use the new `DriveTank`, `DriveSteering` and `DriveJoystick` classes.
- If you're on ev3dev-jessie, use the lower-level API rather than calling `run_*` methods; set parameters before invoking the command, like so:

```python
# Set all parameters
self.left_motor.speed_sp = left_speed_so
self.left_motor.time_sp = time
self.left_motor._set_brake(brake)
self.right_motor.speed_sp = right_speed_sp
self.right_motor.time_sp = time
self.right_motor._set_brake(brake)

# Start the motors
self.left_motor.run_timed()
self.right_motor.run_timed()
```

**Comment by WasabiFan** [comment]
I'm closing this because it isn't an active bug or feature request for tracking purposes; we have other issues and pull requests tracking the work to get Stretch support cleaned up and published so that the nice options are available to everyone and easy to use.
