### ISSUE TITLE
python-ev3dev2 on PyPi

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#485]
I would like to propose that we create a new "project" on PyPi for releasing the 2.x version of ev3dev-lang-python. This way it makes it easy for people to have parallel installs of the 1.x version and the 2.x version the same way we are doing so for the debian package.

**Comment by WasabiFan** [comment]
Agreed. That's also a good opportunity to update the package metadata. I'll look into it tonight.

**Comment by WasabiFan** [comment]
@dlech Did you do the creation/configuration on the PyPi side already or should we do that now?

**Comment by dlech** [comment]
I haven't done anything.

**Comment by WasabiFan** [comment]
That's not true; you updated setup.py with the new name proposed here, so it seemed reasonable to think that you may have done the other half of that change.

**Comment by WasabiFan** [comment]
I updated the final few references to the old package name and did a release to the PyPI test instance (https://test.pypi.org/project/python-ev3dev2/) to confirm everything works; once we tag a commit the CI server should handle the rest. Then @ddemidov will have to add us to the new project because there's no way to create or manage a project from the website until you push the initial version 😆 I was considering swapping it out for my own credentials but I don't see a real reason to given that it doesn't actually solve the problem.

**Comment by WasabiFan** [comment]
Aaaand it's live! Debian and PyPi packages have been published for `2.0.0-beta1`.

https://pypi.org/project/python-ev3dev2/

Last step: @ddemidov is now the sole owner of the new v2 project (because the CI server is Denis) so he'll need to add others again.

**Comment by ddemidov** [comment]
I am not the sole owner anymore

**Comment by WasabiFan** [comment]
Great! I think we're all set then. Let me know if anyone spots issues -- this is a beta so we can package up fixes and release quickly. Docs are up, Debian package is up, PyPi package is up, and I have https://github.com/ev3dev/docker-library/pull/3 open for installing the new package by default.

**Comment by WasabiFan** [comment]
Thanks to everyone helping get this release ready and out! It took something like 8 months but we've done it 😆
