### ISSUE TITLE
UltrasonicSensor - measurement continuously 

### ISSUE THREAD

**Issue by xo1b** [ev3dev/ev3dev-lang-python#597]
- **ev3dev version: 4.14.96-ev3dev-2.3.2-ev3
- **ev3dev-lang-python version:  python3-ev3dev 1.2.0 

i'm fairly new to programming and robotics and struggling with the following. i'm using the Lego Mindstorms EV3 brick and setup the ev3dev2 environment. i would like to program the robot in the way, that it gets the constantly the distance from the ultrasonic sensor and stops when it falls under some value. my first attempt was something like this:

```
from ev3dev2.auto import *

m_right = LargeMotor(OUTPUT_A)
m_left = LargeMotor(OUTPUT_D)
us = UltrasonicSensor(INPUT_4)
us.MODE_US_DIST_CM = 'US_DIST_CM'

def move_timed():
    m_right.run_timed(time_sp=3000, speed_sp=400)
    m_left.run_timed(time_sp=3000, speed_sp=400)
    m_right.wait_while('running')
    m_left.wait_while('running')

def move_stop():
    m_right.stop()
    m_left.stop()

def start_moving():
    dist=us.value()/10
    while dist < 20:
        move_timed()
    else:
        move_stop()

start_moving()
```

when those functions are called us.value() measured the distance only once and not continuously. within the ev3dev-lib there is also the property UltrasonicSensor.distance_centimeters, but I'm not able get its value. though my attempts to get those values failed. when i changed it into:

```
def start_moving():
    dist=us.distance_centimeters
    while dist < 20:
        move_timed()
    else:
        move_stop()
```

i always get "One ore more arguments were out of range or invalid". thankful for any ideas how to get the value continuously!

**Comment by WasabiFan** [comment]
You're close! The main issue is that you only actually try to read the sensor once. `us.distance_centimeters` _is_ the preferred way of doing it, but you have to read the distance repeatedly to get new values. In Python, once you've set a variable like `dist=us.distance_centimeters`, `dist` won't change unless you set it again.

My suggestion would be to do it like this:
- Start the motors. You can call [`my_motor.on`](https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/motors.html#ev3dev2.motor.Motor.on) to start it and have it never automatically stop.
- Loop using Python's `while`. You want to keep looping until `us.distance_centimeters < 20`. Note that we use the property there so that it updates every time.
- Once the loop finishes (i.e., you're within 20cm), stop the motors with `my_motor.stop()`.

Also note that you can use a helper class to control both motors at once: https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/motors.html#multiple-motor-groups. `MoveTank` or `MoveSteering` are probably what you would want.

**Comment by xo1b** [comment]
Thank you!! Your comment put me on the right path and I found a working solution, now I got an obstacle avoiding robot :)
