### ISSUE TITLE
ev3dev2 or ev3dev?

### ISSUE THREAD

**Issue by MrGibbage** [ev3dev/ev3dev-lang-python#626]
Using VS Code. This is pretty much my first time using VS Code and Python, but I have been programming (java mostly) for years. I am following the instructions here:
https://sites.google.com/site/ev3devpython/setting-up-vs-code

but I also see the instructions HERE
https://github.com/ev3dev/ev3dev-lang-python

The big difference between the two of them is this site is using
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank

Where the other site is using
from ev3dev.ev3 import *

Which one should I be using? I am assuming that the ev3dev2 is newer? Also, forgive my likely newbie question, but one import is using ev3dev2.motor and the other is using ev3dev.ev3. What is the difference? Could I use something like 
from ev3dev2.ev3 import *

Next question: When I am writing the code in VS Code, I am getting green lines under many (most??) of the ev3dev classes, such as LargeMotor. Shouldn't the intellisense be picking that up?

Last question: How come I don't have to install any libraries in Python on my PC to make this work? It seems that the libraries would be needed here to compile the code before uploading, but I am guessing there is more to it than that.

- **ev3dev version:** 4.14.96-ev3dev-2.3.2-ev3
- **ev3dev-lang-python version:** 
ii  python3-ev3dev              1.2.0              all                Python language bindings for ev3dev
ii  python3-ev3dev2             2.0.0~beta3        all                Python language bindings for ev3dev

**Comment by WasabiFan** [comment]
The `ev3dev` module is the older version, maintained for compatibility. `ev3dev2` is the newer one which we recommend using in new projects. @ndward's site might not be updated for it.

The green underlines are because you don't have the library installed locally, only on the remote EV3. Python is an interpreted language (rather than compiled) which generally means you don't need libraries installed when coding, only when running. You can install the library on your PC to get auto complete though.
