### ISSUE TITLE
Motor Speed Unreliable

### ISSUE THREAD

**Issue by FalconFX9** [ev3dev/ev3dev-lang-python#642]
Hello, I over the past couple of months, I programmed a robot for the WRO competition. Ev3dev has been not especially reliable (trouble following the line, turns and line following very dependent on battery level, etc). And on the day of the competition, the robot worked fine (at first), but, for some reason, it started being extremely slow -- (turns very slow, line following very slow), despite no changes to the code, and swapping out the motors and sensors. Any idea on why this would happen ? Ev3dev is the only ev3 firmware with an active community, and I want to keep using it, but I need to get these issues figured out to be able to continue using this. Any ideas on how to make it so the motors don't depend on battery level as much (same with the sensors, it's like they polled less when the battery was lower), and how to fix the issue that I had with a massively slow robot? Thanks a bunch
NOTE: looking at data logs -- sensor values and calculated steering values, everything seemed normal

**Comment by WasabiFan** [comment]
It's hard to know what went wrong without more specific investigation. I don't see a reason that low battery would impact code performance, but certainly if you're controlling motors using only duty cycle (rather than setting a speed setpoint) that would be dependent on battery. If you have specific issues we can certainly take a look.

**Comment by dwalton76** [comment]
If the battery is low and your code tells the motors to turn at a specific speed (instead of rotating for a certain number of degrees) then I could picture that causing issues.  I don't know that there is much we can do here without some concrete data to go on.  If you can get some logs on how the motors are performing at various battery levels that might be a good starting point.
