### ISSUE TITLE
python automatic timeout?

### ISSUE THREAD

**Issue by xo1b** [ev3dev/ev3dev-lang-python#668]
**ev3dev version: 4.14.96-ev3dev-2.3.2-ev3
    **ev3dev-lang-python version: python3-ev3dev 1.2.0

I'm neither a technician nor a programmer, so maybe the question is wrong here or the answer is obvious. 

What I'm trying to do, is to map a room with the ev3. Even if it is at the moment very inaccurate (as it depends on the ultrasonic data and distance counter) I encountered a different problem. For the mapping the robot picks randomly one out of twelve actions and marks and obstacle in a png-file. Obviously this system of mapping takes a lot of steps. However after 149 steps the ev3 stops executing the python file. the power is on, it just stops running the file. maybe somebody encountered a similar problem. I send the command to execute the file via ssh and unplug the cable as soon as the robot starts driving. 

all the best 
Gregor

**Comment by WasabiFan** [comment]
Hmmm... There shouldn't be a built-in timeout anywhere, but here are some thoughts.

Does it always stop after the same number of steps/amount of time?

One possibility is that the process is a child of the SSH session and the SSH session times out because it was disconnected... Have you tried running the program from brickman (the on-screen menu)?

Otherwise, have you checked to make sure your script isn't throwing an error? Have you run it and kept the SSH session connected while it runs?

**Comment by xo1b** [comment]
you are right, when I run the program directly from brickman it finishes the steps. 

thanks!
